# Generated by Django 6.0.4 on 2026-05-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('electronics', 'Electronics'), ('gaming', 'Gaming'), ('tools_hardware', 'Tools & Hardware'), ('home_appliances', 'Home & Appliances'), ('other', 'Other')], default='other', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty', models.PositiveIntegerField(help_text='Warranty length in months')),
                ('purchase_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
