# Generated by Django 6.0.4 on 2026-05-09 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='warranty',
            field=models.PositiveIntegerField(choices=[(0, 'No Warranty'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (24, '2 Years'), (36, '3 Years'), (48, '4 Years'), (60, '5 Years')], default=12),
        ),
        migrations.CreateModel(
            name='Maintaining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('repair_type', models.CharField(choices=[('repair', 'Repair'), ('replace', 'Replace Part'), ('service', 'Service'), ('upgrade', 'Upgrade'), ('cleaning', 'Cleaning'), ('inspection', 'Inspection'), ('other', 'Other')], default='repair', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('service_provider', models.CharField(blank=True, max_length=100)),
                ('is_completed', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainings', to='main_app.item')),
            ],
        ),
    ]
