# Generated by Django 6.0.4 on 2026-05-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_item_price_alter_item_warranty_maintaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintaining',
            name='title',
        ),
        migrations.AlterField(
            model_name='maintaining',
            name='date',
            field=models.DateField(verbose_name='Maintaining date'),
        ),
    ]
