# Generated by Django 6.0.4 on 2026-05-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tag_alter_maintaining_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
